import turtle

zolw = turtle.Turtle()
zolw.shape('turtle')
zolw.color('red')
zolw.pensize(7)
zolw.penup()
zolw.goto(-200, 100)
zolw.pendown()
zolw.forward(300)
zolw.right(90)
zolw.forward(150)
zolw.color('green')
zolw.begin_fill()
zolw.circle(25)
zolw.end_fill()
zolw.hideturtle()

zolw2 = turtle.Turtle()
zolw2.shape('turtle')
zolw2.color('blue')
zolw2.pensize(7)
zolw2.penup()
zolw2.goto(-200, -100)

zolw2.pendown()
zolw2.forward(150)
zolw2.left(90)
zolw2.forward(150)
zolw2.begin_fill()
zolw2.color('yellow')
zolw2.circle(25)
zolw2.end_fill()
zolw2.color('blue')
zolw2.circle(25)
zolw2.hideturtle()
turtle.exitonclick()