import turtle
turtle.bgcolor('black')
zolw = turtle.Turtle()
zolw.shape('turtle')
zolw.color(0,0,1)
zolw.begin_fill()
zolw.circle(100)
zolw.penup()
zolw.end_fill()
zolw.forward(250)
zolw.pendown()
zolw.color(0,1,1)
zolw.begin_fill()
zolw.circle(100)
zolw.penup()
zolw.end_fill()
zolw.back(500)
zolw.color(1,1,1)
zolw.pendown()
zolw.begin_fill()
zolw.circle(100)
zolw.penup()
zolw.end_fill()
zolw.hideturtle()
turtle.exitonclick()